#!/bin/sh

set -e

case "${1}" in
    configure)
	    if [ ! -e /usr/bin/http ]; then
		    ln -s /opt/httpie/bin/http /usr/bin/http
	    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "${0} called with unknown argument \`${1}'" >&2
        exit 1
    ;;
esac

exit 0
