#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
	    if [ -h /usr/bin/http ]; then
		    real=$(readlink -f /usr/bin/http)
		    if [ "$real" = "/opt/httpie/bin/http" ]; then
			    rm -f /usr/bin/http
		    fi
	    fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
