#!/bin/sh
set -e

BIN_PATH="/usr/lib/jvm/java-7-oracle-jdk/bin"

for bin in java javaws java_vm jcontrol keytool orbd pack200 policytool rmid \
	     rmiregistry servertool tnameserv unpack200
do
	update-alternatives --remove $bin $BIN_PATH/$bin                            
done

exit 0
