#!/bin/sh
set -e

update-alternatives --install /usr/bin/vi vi /usr/bin/vim73 100
update-alternatives --install /usr/bin/vim vim /usr/bin/vim73 100
update-alternatives --install /usr/bin/vimdiff vimdiff /usr/bin/vim73diff 100
update-alternatives --install /usr/bin/view view /usr/bin/view73 100
update-alternatives --install /usr/bin/rvim rvim /usr/bin/rvim73 100
update-alternatives --install /usr/bin/rview rview /usr/bin/rview73 100
update-alternatives --install /usr/bin/ex ex /usr/bin/ex73 100

exit 0
