#!/bin/sh
#/ Usage: solr <path/to/solr_home> [-Djetty.host=localhost] [-Djetty.port=8983] [-Djetty.logs=/var/log/solr] [-Xmx1024m]
#/ Run the Solr enterprise search platform.
set -e

# show usage
[ "$1" = "--help" ] && {
    grep '^#/'< "$0" |
    cut -c4-
    exit 2
}

if [ `id -u` -ne 0 ]; then
	echo "Solr needs superuser privileges, abort."
	exit 1
fi

# Load SOLR_USER, SOLR_LOGDIR, SOLR_HOST and SOLR_HOME from /etc/default/solr.
[ -r /etc/default/solr ] && . /etc/default/solr

SOLR_USER="${SOLR_USER:='nobody'}"
SOLR_LOGDIR="${SOLR_LOGDIR:='/var/log/solr'}"
SOLR_HOST="${SOLR_HOST:='localhost'}"
SOLR_PORT="${SOLR_PORT:='8983'}"

if [ -n "$1" ]; then
	SOLR_HOME=$1
	shift
fi

if [ -z "$SOLR_HOME" ]; then
	echo "SOLR_HOME is not set, abort."
	exit 1
fi

if [ ! -d "$SOLR_HOME/conf" ]; then
	echo "$SOLR_HOME/conf is missing. Please bootstrap $SOLR_HOME. Abort."
	exit 1
fi

JAVA_OPTS="
  -Djetty.home=/usr/share/solr/jetty
  -Djetty.logs=/var/log/solr/
  -Djetty.host=$SOLR_HOST
  -Djetty.port=$SOLR_PORT
  -server
  -Xms512m
  -Xmx1024m
"

mkdir -p $SOLR_LOGDIR && chown -R $SOLR_USER $SOLR_LOGDIR
mkdir -p $SOLR_HOME/data && chown -R $SOLR_USER $SOLR_HOME/data

exec sudo -u $SOLR_USER java $JAVA_OPTS \
	-Dsolr.solr.home=$SOLR_HOME "$@" \
	-jar /usr/share/solr/jetty/start.jar \
	/usr/share/solr/jetty/etc/jetty.xml >> $SOLR_LOGDIR/solr.log 2>&1
