#!/bin/sh

set -e

SOLR_HOME="$1"

if [ -z "$SOLR_HOME" ]; then
	echo "Usage: $(basename $0) /path/to/new/solr/home"
	exit 1
fi

if [ -d "$SOLR_HOME" ]; then
	echo "Solr home $SOLR_HOME already exists, abort."
	exit 1
fi

mkdir -p $SOLR_HOME
cp -R /usr/share/solr/example/* $SOLR_HOME/
