#!/bin/sh
# preinst script for logstash
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "${1}" in
    install|upgrade)
    ;;

    abort-upgrade)
    ;;

    *)
        echo "${0} called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ -x "/etc/init.d/logstash" ]; then
    if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
        invoke-rc.d logstash stop || true
    else
        /etc/init.d/logstash stop || true
    fi
fi

exit 0
